default_stages: [pre-commit]

default_language_version:
  python: python3.13

repos:
  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      # Formatter
      - id: ruff-format
      # Linter
      - id: ruff-check
        args: [ --fix ]
