name: Privileged
description: You are @hmarcuzzo or he asked you directly to create an issue here. If not, check the other options. 👇
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in FastGear! 🚀

        If you are not @hmarcuzzo or he didn't ask you directly to create an issue here, please start the conversation in a [Question in GitHub Discussions](https://github.com/hmarcuzzo/fastgear/discussions/categories/questions) instead.
  - type: checkboxes
    id: privileged
    attributes:
      label: Privileged issue
      description: Confirm that you are allowed to create an issue here.
      options:
        - label: I'm @hmarcuzzo or he asked me directly to create an issue here.
          required: true
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Add the content of the issue here.
      default: |
        ### Description
        Provide a brief and clear description of the feature or functionality to be implemented.
        Focus on **what** should be done and **why** it is needed.
        
        ### Acceptance Criteria
        Describe how this feature should behave.  
        Prefer **checklist-style items** to make validation objective.
        
        - Given <context>, when <action>, then <expected result>
        - Edge case: <describe expected behavior>
        - Errors are handled gracefully
        - Feature is covered by tests (unit/integration where applicable)
        
        ### Notes
        (Optional)  
        Add any additional context, links, screenshots, references, or technical considerations that may help during implementation.
