name: 'Setup Python and uv'
description: 'Install uv and set the Python version'

inputs:
  python-version:
    description: 'Python version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.14"
        python-version: ${{ inputs.python-version }}

    - name: Cache uv virtualenv
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
        key: uv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ inputs.python-version }}-
