name: CD
run-name: ${{ github.event.workflow_run.display_title }}

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  docs:
    name: Deploy Documentation
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/docs.yaml
    permissions:
      contents: write

  approval:
    name: Manual Approval
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Wait for approval to deploy
        uses: trstringer/manual-approval@v1.12.0
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: hmarcuzzo
          minimum-approvals: 1
          issue-title: "Deploy fastgear"

  release:
    name: Create GitHub Release
    needs: approval
    uses: ./.github/workflows/release.yaml
    permissions:
      contents: write

  publish:
    name: Publish to PyPI
    needs: release
    if: needs.release.outputs.released == 'true'
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
