name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: poetry install --with dev --no-root

      - name: Run Ruff linter
        run: poetry run ruff check .

#  test:
#    name: Test with Pytest
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Python and Poetry
#        uses: ./.github/actions/setup-python-poetry
#        with:
#          python-version: ${{ matrix.python-version }}
#
#      - name: Install dependencies
#        run: poetry install --with test --no-root
#
#      - name: Run tests
#        run: |
#          poetry run pytest
#
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v5
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          slug: hmarcuzzo/fastgear
