name: Linting

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: ./.github/actions/setup-python-uv
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run Ruff linter
        run: uv run ruff check .
