name: Python Compatibility

on:
  workflow_call:

jobs:
  python-versions:
    name: Test with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13", "3.14" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --group test

      - name: Run tests
        run: |
          uv run pytest
